  MODULE('EMPLOYEEAPP005.CLW')
SelectBenefits         PROCEDURE                      !Select a Benefits Record
UpdateLinkBenefitsEmployee PROCEDURE                  !Form LinkBenefitsEmployee
SelectQualification    PROCEDURE                      !Select a Qualification Record
UpdateLinkEmployeeQualification PROCEDURE             !Form LinkEmployeeQualification
ExportView             PROCEDURE(VIEW pBrowseView)
  END
