  MODULE('EMPLOYEESAPP001.CLW')
BrowseEmployees        PROCEDURE                      !Browse the Employees file
ReportEmployees        PROCEDURE                      !Print the Employees File
BrowsePhones           PROCEDURE                      !Browse the Phones file
ReportPhones           PROCEDURE                      !Print the Phones File
BrowseSalary           PROCEDURE                      !Browse the Salary file
ReportSalary           PROCEDURE                      !Print the Salary File
BrowseBenefits         PROCEDURE                      !Browse the Benefits file
ReportBenefits         PROCEDURE                      !Print the Benefits File
BrowseQualification    PROCEDURE                      !Browse the Qualification file
  END
