  MODULE('EMPLOYEESAPP004.CLW')
SelectBenefits         PROCEDURE                      !Select a Benefits Record
UpdateLinkBenefitsEmployee PROCEDURE                  !Form LinkBenefitsEmployee
SelectQualification    PROCEDURE                      !Select a Qualification Record
UpdateLinkEmployeeQualification PROCEDURE             !Form LinkEmployeeQualification
Export_File            PROCEDURE(FILE pTableFile)     !Procedure for manipulating files
  END
