  MODULE('EMPLOYEESAPP002.CLW')
ReportQualification    PROCEDURE                      !Print the Qualification File
BrowseSchools          PROCEDURE                      !Browse the Schools file
ReportSchools          PROCEDURE                      !Print the Schools File
BrowseLinkBenefitsEmployee PROCEDURE                  !Browse the LinkBenefitsEmployee file
ReportLinkBenefitsEmployeeByLin:GuidKey PROCEDURE     !Print the LinkBenefitsEmployee File by Lin:GuidKey
ReportLinkBenefitsEmployeeByLin:BenefitsGuidKey PROCEDURE !Print the LinkBenefitsEmployee File by Lin:BenefitsGuidKey
ReportLinkBenefitsEmployeeByLin:EmployeeGuidKey PROCEDURE !Print the LinkBenefitsEmployee File by Lin:EmployeeGuidKey
BrowseLinkEmployeeQualification PROCEDURE             !Browse the LinkEmployeeQualification file
ReportLinkEmployeeQualificationByLin2:GuidKey PROCEDURE !Print the LinkEmployeeQualification File by Lin2:GuidKey
ReportLinkEmployeeQualificationByLin2:EmployeeGuidKey PROCEDURE !Print the LinkEmployeeQualification File by Lin2:EmployeeGuidKey
  END
