  MODULE('EMPLOYEESAPP003.CLW')
ReportLinkEmployeeQualificationByLin2:QualificationGuidKey PROCEDURE !Print the LinkEmployeeQualification File by Lin2:QualificationGuidKey
SelectSalary           PROCEDURE                      !Select a Salary Record
UpdateEmployees        PROCEDURE                      !Form Employees
SelectEmployees        PROCEDURE                      !Select a Employees Record
UpdatePhones           PROCEDURE                      !Form Phones
UpdateSalary           PROCEDURE                      !Form Salary
UpdateBenefits         PROCEDURE                      !Form Benefits
SelectSchools          PROCEDURE                      !Select a Schools Record
UpdateQualification    PROCEDURE                      !Form Qualification
UpdateSchools          PROCEDURE                      !Form Schools
  END
